{*
 * 2007-2022 LeoTheme
 *
 * NOTICE OF LICENSE
 *
 * LeoGallery is module help you can displays amazing gallery with many features on product page
 *
 * DISCLAIMER
 *
 *  @author    LeoTheme <leotheme@gmail.com>
 *  @copyright 2007-2022 LeoTheme
 *  @license   http://apollotheme.com - prestashop template provider
*}

<div class="leo-config-panel {if $active_tab != 'LeoGalleryMagnifyConfigForm'}hidden{/if}" id="leo-magnify">
    {$form->generateForm($magnifyFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
</div>