{*
 * 2007-2022 LeoTheme
 *
 * NOTICE OF LICENSE
 *
 * LeoGallery is module help you can displays amazing gallery with many features on product page
 *
 * DISCLAIMER
 *
 *  @author    LeoTheme <leotheme@gmail.com>
 *  @copyright 2007-2022 LeoTheme
 *  @license   http://apollotheme.com - prestashop template provider
*}

<div class="leo-config-panel {if $active_tab != 'LeoGallerySliderConfigForm' && $active_tab != 'LeoGallerySliderTabletConfigForm' && $active_tab != 'LeoGallerySliderMobileConfigForm'}hidden{/if}" id="leo-slider">
    <div class="panel">
        <div class="panel-heading">
            <i class="icon-info"></i> {l s='Slider settings' mod='leogallery'}
        </div>
        <div class="form-wrapper">
            <ul class="nav nav-tabs">
                <li class="{if $active_tab == 'LeoGallerySliderConfigForm' || !$active_tab}active{/if}">
                    <a href="#leo-slider-desktop" id="arcu-prompt-desktop-tab" data-toggle="tab">{l s='Desktop' mod='leogallery'}</a>
                </li>
                <li class="{if $active_tab == 'LeoGallerySliderTabletConfigForm'}active{/if}">
                    <a href="#leo-slider-tablet" id="arcu-prompt-desktop-tab" data-toggle="tab">{l s='Tablet' mod='leogallery'}</a>
                </li>
                <li class="{if $active_tab == 'LeoGallerySliderMobileConfigForm'}active{/if}">
                    <a href="#leo-slider-mobile" id="arcu-prompt-desktop-tab" data-toggle="tab">{l s='Mobile' mod='leogallery'}</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane {if $active_tab == 'LeoGallerySliderConfigForm' || !$active_tab}active{/if}" id="leo-slider-desktop">
                    {$form->generateForm($sliderFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
                <div class="tab-pane {if $active_tab == 'LeoGallerySliderTabletConfigForm'}active{/if}" id="leo-slider-tablet">
                    {$form->generateForm($sliderTabletFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
                <div class="tab-pane {if $active_tab == 'LeoGallerySliderMobileConfigForm'}active{/if}" id="leo-slider-mobile">
                    {$form->generateForm($sliderMobileFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
            </div>
        </div>
    </div>
</div>