<?php

/**
 * File from http://PrestaShow.pl
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future.
 *
 * @author    PrestaShow.pl <kontakt@prestashow.pl>
 * @copyright Since 2014 PrestaShow.pl
 * @license   https://prestashow.pl/license
 */

require_once dirname(__FILE__) . "/config.php";

class PShowCookie extends Prestashow\PShowCookie\Module
{

}

//$this->l('Cookies')
//$this->l('ID')
//$this->l('Name')
//$this->l('Group')
//$this->l('Active')
//$this->l('Added')
//$this->l('Cookie editor')
//$this->l('Active')
//$this->l('Enable or disable this cookie.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Name')
//$this->l('Name of the cookie. You can use regular expressions to match multiple cookies.')
//$this->l('Group')
//$this->l('Select the group to which this cookie belongs.')
//$this->l('Description')
//$this->l('Description of the cookie visible to the user.')
//$this->l('Save')
//$this->l('Configuration')
//$this->l('Enabled')
//$this->l('Enable support for Google Consent Mode v2')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Match GCM consents with cookie group consents')
//$this->l('ad_storage')
//$this->l('ad_user_data')
//$this->l('ad_personalization')
//$this->l('analytics_storage')
//$this->l('personalization_storage')
//$this->l('Save')
//$this->l('Configuration')
//$this->l('Automatically collect used cookies')
//$this->l('This feature will automatically collect all cookies used by your website.')
//$this->l('We recommend to disable this function after configuration is done.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Revision')
//$this->l('Useful if you would like to ask your users again for consent after a change in your cookie/privacy policy.')
//$this->l('Disable page interaction')
//$this->l('Creates a dark overlay and blocks the page scroll until consent is expressed.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Hide from bots')
//$this->l('Stops the plugin execution when a bot/crawler is detected, to prevent them from indexing the modal content.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Reload page when consent changes')
//$this->l('Reloads the page when the user changes the consent.')
//$this->l('Enabled')
//$this->l('Disabled')
//$this->l('Consent Modal')
//$this->l('Title')
//$this->l('Content')
//$this->l('Layout')
//$this->l('Cloud')
//$this->l('Bar')
//$this->l('Box')
//$this->l('Position horizontal')
//$this->l('(only for Cloud and Box layout)')
//$this->l('Left')
//$this->l('Center')
//$this->l('Right')
//$this->l('Position vertical')
//$this->l('Top (not for Bar layout)')
//$this->l('Middle (not for Bar layout)')
//$this->l('Bottom')
//$this->l('Preferences Modal')
//$this->l('Layout')
//$this->l('Bar')
//$this->l('Box')
//$this->l('Position horizontal')
//$this->l('(only for Bar layout)')
//$this->l('Left')
//$this->l('Right')
//$this->l('Save')
//$this->l('Cookie groups')
//$this->l('ID')
//$this->l('Name')
//$this->l('Reference')
//$this->l('Added')
//$this->l('Cookie group editor')
//$this->l('Name')
//$this->l('Name of the cookie group')
//$this->l('Reference')
//$this->l('Allowed small letters, numbers and underscores only. Must be unique.')
//$this->l('Description')
//$this->l('Description of the cookie group')
//$this->l('Blocked modules when denied')
//$this->l('Comma separated list of module names which hooks will be blocked when this group is denied')
//$this->l('Default granted')
//$this->l('Is this group granted by default?')
//$this->l('Yes')
//$this->l('No')
//$this->l('Required')
//$this->l('Is this group necessary for the shop to work?')
//$this->l('Yes')
//$this->l('No')
//$this->l('Save')
//$this->l('We use cookies')
//$this->l('This site uses cookies to provide you with the highest level of experience on our site. We also use third-party cookies to improve our services, analyze and then display ads related to your preferences based on analysis of your navigation behavior.')
//$this->l('Essential')
//$this->l('These cookies are essential for the operation of the website and are used to enable basic functions such as page navigation and access to secure areas of the website.')
//$this->l('PHPSESSID is a cookie that is used to identify a user session on a website. A session is a mechanism for maintaining state and user information between requests during a single connection session. The PHPSESSID cookie stores a unique session identifier that is required to process requests and responses between the browser and the server. These cookies last only until the browser is closed.')
//$this->l('PHPSESSID is a cookie that is used to identify a user session on a website. A session is a mechanism for maintaining state and user information between requests during a single connection session. The PHPSESSID cookie stores a unique session identifier that is required to process requests and responses between the browser and the server. These cookies last only until the browser is closed.')
//$this->l('PrestaShop cookies are used to provide the necessary functionality of the website. These cookies do not store any personal information.')
//$this->l('This cookie is used to store the user\'s cookie consent.')
//$this->l('This cookie is used to identify user.')
//$this->l('This cookie is used to identify user.')
//$this->l('This cookie is used to identify user session.')
//$this->l('Analytics')
//$this->l('These cookies allow us to count visits and traffic sources so we can measure and improve the performance of our site. They help us to know which pages are the most and least popular and see how visitors move around the site.')
//$this->l('This cookie is installed by Google Analytics. The cookie is used to calculate visitor, session, campaign data and keep track of site usage for the site\'s analytics report. The cookies store information anonymously and assign a randomly generated number to identify unique visitors.')
//$this->l('This cookie is installed by Google Analytics. The cookie is used to store information of how visitors use a website and helps in creating an analytics report of how the website is doing. The data collected including the number visitors, the source where they have come from, and the pages visited in an anonymous form.')
//$this->l('This cookie is used by Google Analytics to understand user interaction with the website.')
//$this->l('Marketing')
//$this->l('These cookies may be set through our site by our advertising partners. They may be used by those companies to build a profile of your interests and show you relevant adverts on other sites.')
//$this->l('This cookie is set by Facebook to deliver advertisement when they are on Facebook or a digital platform powered by Facebook advertising after visiting this website.')
//$this->l('Other')
//$this->l('These cookies are used to enhance the performance and functionality of our websites but are non-essential to their use. However, without these cookies, certain functionality may become unavailable.')
//$this->l('Cookie Consent Management')
//$this->l('Consents management for the use of cookies.')
//$this->l('Accept all')
//$this->l('Reject all')
//$this->l('Manage Individual preferences')
//$this->l('Manage cookie preferences')
//$this->l('Accept all')
//$this->l('Reject all')
//$this->l('Accept current selection')
//$this->l('Close')
//$this->l('Cookie')
//$this->l('Description')