parent: vt_decor
name: rollcenter
display_name: rollcenter.pl (child vt_decor)
author:
  name: "b4x"
version: 1.0.0

assets:
  use_parent_assets: true

  css:
    all:
      - id: rollcenter-style
        path: assets/css/rollcenter.css

