{**
* 2008-2025 Prestaworld
*
* NOTICE OF LICENSE
*
* The source code of this module is under a commercial license.
* Each license is unique and can be installed and used on only one website.
* Any reproduction or representation total or partial of the module, one or more of its components,
* by any means whatsoever, without express permission from us is prohibited.
*
* DISCLAIMER
*
* Do not alter or add/update to this file if you wish to upgrade this module to newer
* versions in the future.
*
* @author    prestaworld
* @copyright 2008-2025 Prestaworld
* @license https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
* International Registered Trademark & Property of prestaworld
*}
<div class="list-group-item">
    <div class="row form-group presta_form_group">
        <div class="presta_label">
            <label class="control-label title">{l s='Category Default' d='Modules.Prestamassedit.Admin'}</label>
            <div class="actions category_actions">
                <label for="default_category_off" class="btn btn-xs">
                    <input type="radio" id="default_category_off" name="presta_mass_edit[category][default_category][action]" value="off" checked>
                    {l s='Off' d='Modules.Prestamassedit.Admin'}
                </label>
                <label for="default_category_replace" class="btn btn-xs">
                    <input type="radio" id="default_category_replace" name="presta_mass_edit[category][default_category][action]" value="replace">
                    {l s='Replace' d='Modules.Prestamassedit.Admin'}
                </label>
            </div>
        </div>
        <div class="form_input">
            <div class="col-lg-12">
                <div class="clearfix" style="min-height:100px;">
                    {if isset($categories_tree_default) && trim($categories_tree_default) != ''}
                        {* categories_tree_default is trusted HTML generated by the module and is safe *}
                        {$categories_tree_default nofilter}
                    {else}
                        <div class="alert alert-warning">
                            {l s='Categories selection is disabled because you have no categories or you are in a "all shops" context.' d='Modules.Facetedsearch.Admin'}
                        </div>
                    {/if}
                </div>
                <p class="help-block">
                    {l s='Note: If selected category is not already assigned to any of these products, it will be added automatically.' d='Modules.Prestamassedit.Admin'}
                </p>
            </div>
        </div>
    </div>
</div>
{* <!-- Categories --> *}
<div class="list-group-item">
    <div class="row form-group presta_form_group">
        <div class="presta_label">
            <label class="control-label title">{l s='Categories' d='Modules.Prestamassedit.Admin'}</label>
            <div class="actions category_actions">
                <label for="categories_off" class="btn btn-xs">
                    <input type="radio" id="categories_off" name="presta_mass_edit[category][categories][action]" value="off" checked>
                    {l s='Off' d='Modules.Prestamassedit.Admin'}
                </label>
                <label for="categories_add" class="btn btn-xs">
                    <input type="radio" id="categories_add" name="presta_mass_edit[category][categories][action]" value="add">
                    {l s='Add' d='Modules.Prestamassedit.Admin'}
                </label>
                <label for="categories_remove" class="btn btn-xs">
                    <input type="radio" id="categories_remove" name="presta_mass_edit[category][categories][action]" value="remove">
                    {l s='Remove' d='Modules.Prestamassedit.Admin'}
                </label>
                <label for="categories_remove_all" class="btn btn-xs">
                    <input type="radio" id="categories_remove_all" name="presta_mass_edit[category][categories][action]" value="remove_all">
                    {l s='Remove All' d='Modules.Prestamassedit.Admin'}
                </label>
                <label for="categories_replace_all" class="btn btn-xs">
                    <input type="radio" id="categories_replace_all" name="presta_mass_edit[category][categories][action]" value="replace_all">
                    {l s='Replace All' d='Modules.Prestamassedit.Admin'}
                </label>
            </div>
        </div>
        <div class="form_input">
            <div class="col-lg-12">
                <div class="clearfix" style="min-height:100px;">
                    {if isset($categories_tree) && trim($categories_tree) != ''}
                        {* categories_tree is trusted HTML generated by the module and is safe *}
                        {$categories_tree nofilter}
                    {else}
                        <div class="alert alert-warning">
                            {l s='Categories selection is disabled because you have no categories or you are in a "all shops" context.' d='Modules.Facetedsearch.Admin'}
                        </div>
                    {/if}
                </div>
            </div>
        </div>
    </div>
</div>
